languageCode = "en"
languageName = "English"
weight = 1
title = "Aurelia Abayas"
contentDir = 'content/en'


[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "message us to order‏ | shipping to gcc countries & the UK"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
   name = "Aurelia Abayas"
   image = "img/avatar.png"
   headline = "Message us to order!"
   bio = ""
    links = [
      { whatsapp = "https://wa.me/966539821350/" },
      { instagram = "https://www.instagram.com/aurelia.abayas?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==/" }
    ]